spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/myhero;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
