CREATE TABLE IF NOT EXISTS  JORNADA_TRABALHO(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) );

INSERT INTO JORNADA_TRABALHO (descricao) VALUES ('PJ');
INSERT INTO JORNADA_TRABALHO (descricao) VALUES ('CLT');
